# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: eds-figma-broker


trigger:
  batch: true
  branches:
    include:
      - master
      - features/*
  paths:
    include:
    # This cant be a variable
      - /figma-broker
pr:
  paths:
    exclude:
    - /storefront

variables:
  imageName: 'eds-figma-broker:$(Build.BuildId)-$(Build.SourceBranchName)'
  rootFolder: /figma-broker

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: docker build -f .$(rootFolder)/Dockerfile -t $(imageName) .$(rootFolder)
  displayName: 'Docker build'
