name: _Purge cdn
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
# Because of limitations in how to set environment context when calling reusable workflows,
# we are using ENV variables directly in this one. Not pretty, but it works.

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  AZURE_CDN_PROFILE_NAME: ${{ vars.AZURE_CDN_PROFILE_NAME }}
  AZURE_CDN_ENDPOINT_NAME: ${{ vars.AZURE_CDN_ENDPOINT_NAME }}
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
jobs:
  purge:
    name: Purge the cdn to refresh cache
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Az CLI login 🔑 # Using federated credential
        uses: azure/login@v1
        with:
          client-id: d58b2e85-2d34-4cdb-ad70-5f2b767dd8e2
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          allow-no-subscriptions: true
      - name: debug
        shell: bash
        run: echo "Profile name - ${{ env.AZURE_CDN_PROFILE_NAME }}"
      - name: Purge CDN endpoint 🚮
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name ${{ env.AZURE_CDN_PROFILE_NAME }} --name ${{ env.AZURE_CDN_ENDPOINT_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
      - name: logout 🔓
        run: |
          az logout
        if: always()
      - name: log-errors-to-slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
