name: Publish lab-react
on:
  workflow_dispatch:
    inputs:
      npm-tag:
        description: 'Tag for npm package (next | latest)'
        required: true
        default: 'next'
      storybook-slot:
        description: 'Slot for Storybook (development | production | lab | test)'
        required: false
        default: 'lab'
jobs:
  setup:
    uses: equinor/design-system/.github/workflows/_setup.yml@develop
    with:
      cacheKey: ${{ github.sha }}
      checkout_paths: packages/eds-core-react packages/eds-tokens packages/eds-icons packages/eds-lab-react packages/eds-utils
      stage: ${{ github.event.inputs.storybook-slot }}
      tag: ${{ github.event.inputs.npm-tag }}
  packages:
    name: Process packages
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Use "setup" cache
        uses: actions/cache@v3
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}
      - name: Use "dist" cache
        uses: actions/cache@v3
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-dist-${{ needs.setup.outputs.stage }}-lab
      - name: Build packages
        run: node_modules/.bin/pnpm run build
      - name: Build lab Storybook
        run: node_modules/.bin/pnpm build:storybook:lab
  publish-utils-package:
    name: Publish utils to npm
    runs-on: ubuntu-latest
    needs: [packages, setup]
    steps:
      - name: Use "dist" cache
        uses: actions/cache@v3
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-dist-${{ needs.setup.outputs.stage }}-lab
      - name: Publish to npm
        run: |
          node_modules/.bin/pnpm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}
          node_modules/.bin/pnpm --filter @equinor/eds-utils publish --access public --tag ${{ needs.setup.outputs.tag }} --no-git-checks
  publish-lab-package:
    name: Publish lab to npm
    runs-on: ubuntu-latest
    needs: [publish-utils-package, setup]
    steps:
      - name: Use "dist" cache
        uses: actions/cache@v3
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-dist-${{ needs.setup.outputs.stage }}-lab
      - name: Publish to npm
        run: |
          node_modules/.bin/pnpm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}
          node_modules/.bin/pnpm --filter @equinor/eds-lab-react publish --access public --tag ${{ needs.setup.outputs.tag }} --no-git-checks
  # TODO: Delete when new storybook is being used
  publish-old-storybook:
    name: Publish Storybook
    needs: [setup, packages]
    uses: equinor/design-system/.github/workflows/_azure_docker.yml@develop
    with:
      stage: ${{ needs.setup.outputs.stage }}
      cacheKey: ${{ github.sha }}-dist-${{ needs.setup.outputs.stage }}-lab
      dockerfilePath: './packages/eds-lab-react/Dockerfile.storybook'
    secrets:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  publish-storybook:
    needs: [setup, packages]
    name: Build & Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Use cache with storybook files
        id: use-cache-storybook
        uses: actions/cache@v3
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: ${{ github.sha }}-dist-production-lab-storybook
      - name: Deploy the website
        id: deploy-website
        uses: tibor19/static-website-deploy@v2
        with:
          enabled-static-website: 'true'
          folder: 'packages/eds-lab-react/storybook-build'
          public-access-policy: 'container'
          connection-string: ${{ secrets.AZ_STORAGE_STORYBOOK_LAB_CONNECTION_STRING }}
