name: Purge CDN
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for Storybook (development | production)'
        required: false
        type: choice
        options:
          - development
          - production
        default: 'development'
permissions:
  id-token: write
jobs:
  purge-cdn:
    if: inputs.environment == 'production'
    name: Purge cdn
    uses: equinor/design-system/.github/workflows/_purge_cdn.yaml@develop
    secrets: inherit
    with:
      environment: production
