name: Set up Azure environment
on: workflow_dispatch

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to azure 🔑
        id: login-to-azure
        uses: azure/login@v1
        with:
          # TODO: Start using federated credentials
          creds: ${{ secrets.AZURE_CREDENTIALS_2022 }}
      - name: Show Azure account
        run: az account show
      # Checkout internal repository where the bicep files are located
      - name: Checout internal 🛎️
        id: checkout-internal
        uses: actions/checkout@v3
        with:
          repository: 'equinor/design-system-internal'
          ref: main
          token: ${{ secrets.PAT_INTERNAL }}
      # Do the actual deployment
      - name: deploy 🚀
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: northeurope
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          template: .azure/main.bicep
          parameters: 'location=northeurope'
          failOnStdErr: false
      - name: logout 🔓
        run: |
          az logout
        if: always()
      - name: log-errors-to-slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()
