name: Testing actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      test-value:
        description: 'Test'
        required: false
        default: 'development'
jobs:
  setup-environment:
    uses: equinor/design-system/.github/workflows/setup-env-vars.yml@v1
    with:
      environment: '${{ github.event.inputs.test-value }}'
  print-variables:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Print slot outputs
        run: echo ${{ needs.setup-environment.outputs.environment }}
