name: Testing actions
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      test-value:
        description: 'Test'
        required: false
        default: 'development'
jobs:
  setup:
    uses: equinor/design-system/.github/workflows/setup.yml@develop
    with:
      environment: ${{ github.event.inputs.test-value }}
      cacheKey: some-key
    secrets:
      npmToken: some-token
  print-variables:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Workflow environment
        run: echo ${{ needs.setup.outputs.environment }}
      - name: Workflow tag
        run: echo ${{ needs.setup.outputs.tag }}
      - name: Input output
        run: echo ${{ github.event.inputs.test-value }}
  check-cache:
    name: Check cache
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Lookup cache
        uses: actions/cache@v2
        with:
          path: |
            ./*
            ~/.pnpm-store
          key: some-key
